name: 'Initialize the Python environemnt'
description: 'Initialize the Python environment by checking out the repo and executing pip install then caching it'
inputs:
  python-version:
    description: 'Version of the python interpreter to use'
    required: true
runs:
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install --no-cache-dir -U pip .['dev']