name: CI
on: [push]
jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - name: Install dependencies
        run: pip install -U pip .['dev']
      - name: Lint check with flake8
        run: scripts/ci.py lint
      - name: Format check with black
        run: scripts/ci.py format
      - name: Type check with mypy
        run: scripts/ci.py type 
      - name: CVE check with pip-audit
        run: scripts/ci.py cve
      - name: Security check with bandit
        run: scripts/ci.py security
  testing: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - name: Install dependencies
        run: pip install -U pip .['dev']
      - name: Run integration tests
        run: echo 'dummy integration test step...'