name: CI
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: ./.github/actions/init-python-env
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint check with flake8
        run: scripts/ci.py lint
      - name: Format check with black
        run: scripts/ci.py format
      - name: Type check with mypy
        run: scripts/ci.py type 
      - name: CVE check with pip-audit
        run: scripts/ci.py cve
      - name: Security check with bandit
        run: scripts/ci.py security